apache/seatunnel-website

docusaurus.config.js
=> Add historical document link.

src/css/custom.css, src/pages/home/index.jsx, src/pages/home/index.less
small screen and mobile css style adaptation
=> small screen and mobile css style adaptation

src/pages/home/languages.json
English page Chinese translation
=> English page Chinese translation

README.md, docusaurus.config.js, src/pages/home/index.less, src/pages/team/index.js, src/pages/team/index.less, src/pages/team/languages.json, src/pages/user/index.js, src/pages/user/index.less, src/styles/variable.less
=> team page add.

docusaurus.config.js, i18n/zh-CN/docusaurus-theme-classic/navbar.json, src/pages/team/index.js, src/pages/team/index.less, src/pages/user/index.less
=> navbar i18n support.

community/contribution_guide/committer.md
=> Add Committer Guide

src/pages/user/languages.json
=>  Update languages.json

src/pages/home/index.jsx
=> Update HomePage Image

.github/workflows/deploy.yml, tools/build-docs.sh
=> Fix deploy bug

src/pages/home/index.jsx
=> [Bug][doc] Fix the QUICK START in the home page cannot jump normally

.github/workflows/deploy.yml, README.md, README_ZH.md, docs/introduction.md, tools/build-docs.sh
Add scheduled deployment and document optimization
=> Add scheduled deployment and document optimization

tools/build-docs.sh
Build documentation script optimization
=> [Chore][Docs] Build documentation script optimization

tools/build-docs.sh
-r could regexp replace in my linux server but
could not success in my laptop, which using bash
`GNU bash, version 5.1.8(1)-release`
=> Enhance sed regexp with `-E` instead of `-r`

docusaurus.config.js
Don't merge until https://github.com/apache/incubator-seatunnel/pull/1611 merged
=> Change site attr to auto collapse and correct next doc index

src/pages/team/index.js, src/pages/team/languages.json
[Feature][docs] Add committers to team page
https://github.com/apache/incubator-seatunnel/issues/1604
=> [Feature][docs] Add committers to team page

docusaurus.config.js, src/pages/home/index.jsx
We reorder our document in this path and move next
release after `1.x(not apache release)` and before
all versions
=> [doc] Change document order

versioned_docs/version-2.1.0/flink/quick-start.md, versioned_docs/version-2.1.1/start/local.mdx
=> docs: flink 1.14.x cannot runable, must limit flink version in docs until resove it.

versioned_docs/version-2.1.2/start/kubernetes.mdx
update seatunnel doc on kubernetes
=> [Hot-Fix] update seatunnel doc on kubernetes

docusaurus.config.js
=> feat: Hidden Chinese and English switch

HOW_DOC_WORK.md
=> [Improve][docs] Change the document to the correct project name

src/pages/team/languages.json
Add new committers' information.
=> [Improve][docs] Add new committers

versioned_docs/version-2.2.0-beta/connector-v2/source/IoTDB.md
=>  Fix IoTDB source docs

blog/2022-09-20-A-tutorial-to-help-you develop-a-SeaTunnel-Connector-hand-by-hand-while-avoiding -pitfalls.md
…r-hand-by-hand-while-avoiding -pitfalls.md
=> add news Blog 

versioned_docs/version-2.2.0-beta/start/kubernetes.mdx
Kubernetes, Docker and Helm are names, so they need to be capitalized
=> Fixed capitalization

versioned_docs/version-2.2.0-beta/start-v2/local.mdx, versioned_docs/version-2.2.0-beta/start/local.mdx
Modify Quick Start and  Quick Start  V2 doc.
=> [doc]Modify Quick Start doc

src/pages/versions/config.json
=> [Hotfix][Docs] Fix link

docusaurus.config.js, src/pages/home/index.jsx
=> [Hotfix][Docs] Fix home page link

src/pages/team/languages.json
move dijiekstra from committer to ppmc
=> [seatunnel] move dijiekstra from committer to ppmc

src/pages/team/index.js
=> [Doc] Modify PPMC to PMC

versioned_docs/version-2.3.2/start-v2/locally/deployment.md
fixed a typo in the plugin install command
=> [doc] Update deployment.md to fix typo

versioned_sidebars/version-2.1.3-sidebars.json
=> [title] fix 2.1.3 sink title

versioned_docs/version-2.3.2/faq.md
=> [Fix] Delete outdated QA 

versioned_docs/version-2.3.2/contribution/setup.md
When I executed it（seatunnel-examples/seatunnel-flink-connector-v2-example/src/main/java/org/apache/seatunnel/example/flink/v2/SeaTunnelApiExample.java）, it didn't produce anything like what the document expected
I hope you can help review
=> Adjust 'Set Up Develop Environment' page output

versioned_docs/version-2.3.1/connector-v2/sink/StarRocks.md
node_urls -> nodeUrls
node_urls doesn't work
=> [doc] property name fix

docusaurus.config.js
<https://github.com/apache/seatunnel/issues/5246>
=> [Feature][Doc] Add global search functionality to the official website documentation. #5246

versioned_docs/version-2.3.3/start-v2/docker/docker.md
Add documents for Zeta engine running on Docker
@jbonofre @Humbedooh
=> [Feature][Doc] Add Docker Doc #5513

seatunnel_web_versioned_docs/version-1.0.0/deploy.md
=> [Bug] [Doc] [Web] Fix web doc bug #5855

versioned_docs/version-2.3.0/about.md, versioned_docs/version-2.3.1/about.md, versioned_docs/version-2.3.2/about.md, versioned_docs/version-2.3.3/about.md
=> [BUG][DOC] update quick start links

versioned_docs/version-2.3.6/seatunnel-engine/hybrid-cluster-deployment.md
link https://github.com/apache/seatunnel/pull/7306
=> [Fix][Doc] Fix hybrid cluster deployment document display error

versioned_sidebars/version-2.3.6-sidebars.json
link https://github.com/apache/seatunnel/pull/7310
=> [Fix][Doc] Fix miss sink-options-placeholders.md in sidebars

src/pages/team/languages.json
Add new committer named Mohammad Arshad.
=> [Improve][Team] Add new committer named Mohammad Arshad

src/pages/team/languages.json
=> [Improve][Team] Add new committer named 

community/submit_guide/submit-code.md, i18n/zh-CN/docusaurus-plugin-content-docs-community/current/submit_guide/submit-code.md
=> [Improve] Update submit code guide

i18n/zh-CN/docusaurus-plugin-content-docs/version-2.3.8/concept/schema-feature.md
…on [columnName]
[Fix][Doc] schema.constraintKeys.constraintColumns.* config need option [columnName]
=> [Fix][Doc] config need option [columnName]

src/pages/home/languages.json
Fixes broken link to the connectors page.
=> [Fix][Doc] fix link to connectors

tools/version.js
=> [Fix] Use dynamic import for execa in version.js

i18n/zh-CN/docusaurus-plugin-content-docs/version-2.3.11/transform-v2/table-filter.md
2.3.11 Sidebar Transform-V2 text title TableFilter incorrect spelling
=> [Fix][Doc] Fix transform-v2 text title
